package telas;

import cliente.Cliente;
import cliente.DadosCliente;
import cliente.RegrasCliente;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.util.Date;


public class TelaFazerPedido extends javax.swing.JFrame {
    
    DadosCliente dadosCliente = new DadosCliente();
    Cliente cliente = new Cliente();
    RegrasCliente regrasCliente = new RegrasCliente();



    private static void addRow(Object[] object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public TelaFazerPedido() {
        initComponents();
        setLocationRelativeTo(null);
        //habilitarDesabilitarCampos(false);
        //mensagem();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbAtualizarCardapio = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jbAtualizarCardapio1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jNomeCliente = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCPF = new javax.swing.JFormattedTextField();
        jNomeCliente1 = new javax.swing.JLabel();
        jbFinalizarPedido = new javax.swing.JButton();
        jbCancelarPedido = new javax.swing.JButton();
        jbIncluir = new javax.swing.JButton();
        jbRetirar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtValorTotal = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jbIniciarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TELA DE PEDIDO");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(19, 18, 19));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jbAtualizarCardapio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbAtualizarCardapio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-actualizar-40.png"))); // NOI18N
        jbAtualizarCardapio.setText("ATUALIZAR LISTA");
        jbAtualizarCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarCardapioActionPerformed(evt);
            }
        });

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Valor(R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtProdutos);
        if (jtProdutos.getColumnModel().getColumnCount() > 0) {
            jtProdutos.getColumnModel().getColumn(1).setMinWidth(200);
            jtProdutos.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtProdutos.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jbAtualizarCardapio1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbAtualizarCardapio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-actualizar-40.png"))); // NOI18N
        jbAtualizarCardapio1.setText("ATUALIZAR LISTA");
        jbAtualizarCardapio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarCardapio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbAtualizarCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jbAtualizarCardapio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbAtualizarCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jbAtualizarCardapio1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(673, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        jNomeCliente.setText("NOME:");

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        jNomeCliente1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jNomeCliente1.setForeground(new java.awt.Color(255, 255, 255));
        jNomeCliente1.setText("CPF:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(jtfCPF))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jbFinalizarPedido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbFinalizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/completed-task(2).png"))); // NOI18N
        jbFinalizarPedido.setText("Finalizar Pedido");
        jbFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarPedidoActionPerformed(evt);
            }
        });

        jbCancelarPedido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-cancelar-34.png"))); // NOI18N
        jbCancelarPedido.setText("Cancelar");
        jbCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarPedidoActionPerformed(evt);
            }
        });

        jbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-avançar-50.png"))); // NOI18N

        jbRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-voltar-50.png"))); // NOI18N

        jtPedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quant", "Descrição", "Valor(R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtPedido);
        if (jtPedido.getColumnModel().getColumnCount() > 0) {
            jtPedido.getColumnModel().getColumn(0).setMinWidth(70);
            jtPedido.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtPedido.getColumnModel().getColumn(0).setMaxWidth(70);
            jtPedido.getColumnModel().getColumn(2).setMinWidth(200);
            jtPedido.getColumnModel().getColumn(2).setPreferredWidth(200);
            jtPedido.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITENS DO PEDIDO");

        jtValorTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtValorTotalActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("R$");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jbIniciarPedido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbIniciarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-reproduzir-filled-36.png"))); // NOI18N
        jbIniciarPedido.setText("INICIAR PEDIDO");
        jbIniciarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbIniciarPedido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbIncluir)
                            .addComponent(jbRetirar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jbCancelarPedido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbFinalizarPedido))
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(jbIncluir)
                                .addGap(62, 62, 62)
                                .addComponent(jbRetirar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbIniciarPedido)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jbAtualizarCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarCardapioActionPerformed
        // Atualiza o cardápio e preços na tela de pedidos:
        
        /*
        
        try {

            modelCardapio = dadosCardapio.ListarCardapio(cardapio);
        } catch (Exception ex) {
            Logger.getLogger(TelaFazerPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Carregar o cardápio na tela do banco de dados       
        jtf1.removeAll();
        jtf1.setText(modelCardapio.get(0).getNome_cardapio());
        jtfValor1.setText(String.valueOf(modelCardapio.get(0).getValor_cardapio()));

        jtf2.removeAll();
        jtf2.setText(modelCardapio.get(1).getNome_cardapio());
        jtfValor2.setText(String.valueOf(modelCardapio.get(1).getValor_cardapio()));

        jtf3.removeAll();
        jtf3.setText(modelCardapio.get(2).getNome_cardapio());
        jtfValor3.setText(String.valueOf(modelCardapio.get(2).getValor_cardapio()));

        jtf4.removeAll();
        jtf4.setText(modelCardapio.get(3).getNome_cardapio());
        jtfValor4.setText(String.valueOf(modelCardapio.get(3).getValor_cardapio()));

        jtf5.removeAll();
        jtf5.setText(modelCardapio.get(4).getNome_cardapio());
        jtfValor5.setText(String.valueOf(modelCardapio.get(4).getValor_cardapio()));

        jtf6.removeAll();
        jtf6.setText(modelCardapio.get(5).getNome_cardapio());
        jtfValor6.setText(String.valueOf(modelCardapio.get(5).getValor_cardapio()));

        jtf7.removeAll();
        jtf7.setText(modelCardapio.get(6).getNome_cardapio());
        jtfValor7.setText(String.valueOf(modelCardapio.get(6).getValor_cardapio()));

        jtf8.removeAll();
        jtf8.setText(modelCardapio.get(7).getNome_cardapio());
        jtfValor8.setText(String.valueOf(modelCardapio.get(7).getValor_cardapio()));

        jtf9.removeAll();
        jtf9.setText(modelCardapio.get(8).getNome_cardapio());
        jtfValor9.setText(String.valueOf(modelCardapio.get(8).getValor_cardapio()));
        
        
        */


    }//GEN-LAST:event_jbAtualizarCardapioActionPerformed

    private void jbIniciarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarPedidoActionPerformed
        //Habilita os campos para a entrada do pedido e Solicita que um nome seja inserido antes de iniciar o pedido.

        if (jtfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Entrar com seu nome antes de aperta o botão iniciar pedido", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

        } else {
            habilitarDesabilitarCampos(true);
        }


    }//GEN-LAST:event_jbIniciarPedidoActionPerformed

    private void jtValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtValorTotalActionPerformed

    private void jbCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarPedidoActionPerformed
        // Se o botão cancelar for apertado ele limpa os campos da tela e desabilita alguns botões:
        limparCampos();
        habilitarDesabilitarCampos(false);
    }//GEN-LAST:event_jbCancelarPedidoActionPerformed

    private void jbFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarPedidoActionPerformed
        // Salva as informações do pedido no banco de dados:
        
        cliente.setNome(jtfNome.getText());
        cliente.setCpf(jtfCPF.getText());
        
        try {
            regrasCliente.cadastrarCliente(cliente);

        } catch (Exception ex) {
            Logger.getLogger(TelaFazerPedido.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
            
            
            /*
            
            Pedido pedido = new Pedido();
            venda = new Venda();
            
            //Cadastra o cliente que irá fazer o pedido
            modelCliente.setNome(jtfNome.getText());
            try {
            dadosCliente.cadastrarCliente(modelCliente);
            pedido.setCod_cliente(dadosCliente.retornaIdCliente());

            // Cadastra o pedido na tabela pedido do banco de dados
            int cont = jtPedido.getRowCount();
            for (int i = 0; i < cont; i++) {
            pedido.setDescricao((String) jtPedido.getValueAt(i, 0));
            pedido.setCod_cliente(dadosCliente.retornaIdCliente());
            pedido.setData(converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            venda.setValor((Double) jtPedido.getValueAt(i, 1));
            dadosPedido.cadastrarPedido(pedido);
            pedido.setCod(dadosPedido.retornaIdPedido());
            
            dadosVenda.registrarVenda(pedido, venda);
            }
            JOptionPane.showMessageDialog(this, "Pedido finalizado", "INFORMAÇÃO", JOptionPane.INFORMATION_MESSAGE);
            
            } catch (Exception ex) {
            Logger.getLogger(TelaFazerPedido.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Problema no pedido. Tente novamente", "ERRO", JOptionPane.ERROR);
            }
            
            limparCampos();
            habilitarDesabilitarCampos(false);
            
            */
      
       

    }//GEN-LAST:event_jbFinalizarPedidoActionPerformed

    private void jbAtualizarCardapio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarCardapio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAtualizarCardapio1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Converte data tipo date para o formato americano yyyy/MM/dd também tipo
     * date Date para Date
     *
     * @param pData
     * @return
     * @throws Exception
     */
    public java.sql.Date converterDataParaDateUS(Date pData) throws Exception {
        SimpleDateFormat formatarDate = new SimpleDateFormat("yyyy/MM/dd");
        String dataString = formatarDate.format(pData);
        if (pData == null || pData.equals("")) {
            return null;
        }

        java.sql.Date date = null;
        try {
            DateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
            date = new java.sql.Date(((java.util.Date) formatter.parse(dataString)).getTime());
        } catch (ParseException e) {
            throw e;
        }
        return date;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFazerPedido().setVisible(true);
            }
        });
    }

    /**
     * vai somando os valores na medida que os produtos são adicinados.
     */
    private void somarValorTotal() {
        double soma = 0;
        int cont = jtPedido.getRowCount();
        for (int i = 0; i < cont; i++) {
            double valor = (double) jtPedido.getValueAt(i, 1);
            soma += valor;
        }
        jtValorTotal.setText(String.valueOf(soma));
    }

    /**
     * Vai adicionando itens na lista
     */
    private void adicionarItensaoPedido() {
        
        /*
        
        DefaultTableModel modelo = (DefaultTableModel) jtPedido.getModel();
        
        //Inserindo uma nova linha na tabela
        int cont = 0;
        for (int i = 0; i < cont; i++) {
            modelo.setNumRows(0);
        }
        
        //adicionar itens na tabela
        modelo.addRow(new Object[]{
            cardapio1.getNome_cardapio(),
            cardapio1.getValor_cardapio()
        });
        
        */
        
    }

    /*
    Limpa os dados da tela e da tabela.
    */
    private void limparCampos() {
        jtfNome.setText("");
        jtValorTotal.setText("");

        DefaultTableModel modelo = (DefaultTableModel) jtPedido.getModel();
        modelo.setNumRows(0);

    }

   
    /**
     * Habilita(true)/Desabilita(false) campos da tela.
     * @param condicao 
     */
    private void habilitarDesabilitarCampos(boolean condicao) {
        
        /*
        jbProduto1.setEnabled(condicao);
        jbProduto2.setEnabled(condicao);
        jbProduto3.setEnabled(condicao);
        jbProduto4.setEnabled(condicao);
        jbProduto5.setEnabled(condicao);
        jbProduto6.setEnabled(condicao);
        jbProduto7.setEnabled(condicao);
        jbProduto8.setEnabled(condicao);
        jbProduto9.setEnabled(condicao);
        jbFinalizarPedido.setEnabled(condicao);
        jbDeletarItem.setEnabled(condicao);

*/

    }

    private void mensagem() {
        JOptionPane.showMessageDialog(this, "Entrar com seu nome e apertar IniciarPedido", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNomeCliente;
    private javax.swing.JLabel jNomeCliente1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbAtualizarCardapio;
    private javax.swing.JButton jbAtualizarCardapio1;
    private javax.swing.JButton jbCancelarPedido;
    private javax.swing.JButton jbFinalizarPedido;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JButton jbIniciarPedido;
    private javax.swing.JButton jbRetirar;
    private javax.swing.JTable jtPedido;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JTextField jtValorTotal;
    private javax.swing.JFormattedTextField jtfCPF;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
