/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import produto.DadosProduto;
import produto.Produto;
import tipo.DadosTipo;
import tipo.Tipo;

/**
 *
 * @author lgdal
 */
public class TelaCadastraProdutos extends javax.swing.JFrame {

    Tipo tipo = new Tipo();
    DadosTipo dadosTipo = new DadosTipo();
    ArrayList<DadosTipo> listaDadosTipos = new ArrayList<>();

    Produto produto = new Produto();
    DadosProduto dadosProduto = new DadosProduto();
    ArrayList<DadosProduto> listaDadosProduto = new ArrayList<>();

    /**
     * Creates new form TelaCadastraTipos
     */
    public TelaCadastraProdutos() {
        initComponents();
        carregarTipos();
        carregarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfProduto = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTipos = new javax.swing.JTable();
        jrbIndisponivel = new javax.swing.JRadioButton();
        jrbDisponivel = new javax.swing.JRadioButton();
        jbAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Tipo", "Disponibilidade", "Valor(R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProdutos);
        if (jtProdutos.getColumnModel().getColumnCount() > 0) {
            jtProdutos.getColumnModel().getColumn(0).setMinWidth(100);
            jtProdutos.getColumnModel().getColumn(0).setPreferredWidth(100);
            jtProdutos.getColumnModel().getColumn(0).setMaxWidth(100);
            jtProdutos.getColumnModel().getColumn(2).setMinWidth(130);
            jtProdutos.getColumnModel().getColumn(2).setPreferredWidth(130);
            jtProdutos.getColumnModel().getColumn(2).setMaxWidth(130);
            jtProdutos.getColumnModel().getColumn(3).setMinWidth(130);
            jtProdutos.getColumnModel().getColumn(3).setPreferredWidth(130);
            jtProdutos.getColumnModel().getColumn(3).setMaxWidth(130);
            jtProdutos.getColumnModel().getColumn(4).setMinWidth(100);
            jtProdutos.getColumnModel().getColumn(4).setPreferredWidth(100);
            jtProdutos.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produto:");

        jtfProduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-reproduzir-filled-36.png"))); // NOI18N
        jbCadastrar.setText("CADASTRAR");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-cancelar-34.png"))); // NOI18N
        jbCancelar.setText("CANCELAR");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-lixo-34.png"))); // NOI18N
        jbExcluir.setText("EXCLUIR");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Preço (R$):");

        jtfPreco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jtTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtTipos);
        if (jtTipos.getColumnModel().getColumnCount() > 0) {
            jtTipos.getColumnModel().getColumn(0).setMinWidth(130);
            jtTipos.getColumnModel().getColumn(0).setPreferredWidth(130);
            jtTipos.getColumnModel().getColumn(0).setMaxWidth(130);
        }

        jrbIndisponivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbIndisponivel.setForeground(new java.awt.Color(204, 204, 204));
        jrbIndisponivel.setText("Indisponível");
        jrbIndisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIndisponivelActionPerformed(evt);
            }
        });

        jrbDisponivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbDisponivel.setForeground(new java.awt.Color(204, 204, 204));
        jrbDisponivel.setText("Disponível");
        jrbDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDisponivelActionPerformed(evt);
            }
        });

        jbAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-actualizar-40.png"))); // NOI18N
        jbAtualizar.setText("ATUALIZAR");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtfProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbDisponivel)
                                        .addGap(290, 290, 290)
                                        .addComponent(jrbIndisponivel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbAtualizar)
                                .addGap(28, 28, 28)))
                        .addComponent(jbCadastrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbIndisponivel)
                            .addComponent(jrbDisponivel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbExcluir)
                            .addComponent(jbCancelar)
                            .addComponent(jbCadastrar)
                            .addComponent(jbAtualizar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:

        produto.setNome(jtfProduto.getText());

        if (jrbDisponivel.isSelected()) {
            produto.setDisponibilidade("Sim");
        } else {
            produto.setDisponibilidade("Faltando");
        }

        produto.setValorUnitario(Double.valueOf(jtfPreco.getText()));

        try {
            int linha = jtTipos.getSelectedRow();
            int codigoTipo = (int) jtTipos.getValueAt(linha, 0);
            String descricao = (String) jtTipos.getValueAt(linha, 1);

            tipo.setCod_tipo(codigoTipo);
            tipo.setDescricao(descricao);

            produto.setTipo(tipo);

            dadosProduto.cadastrarProduto(produto);

        } catch (Exception ex) {
            Logger.getLogger(TelaCadastraProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }

        carregarTipos();
        carregarProdutos();
        limparCampos();


    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        carregarTipos();
        limparCampos();

    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:

        try {
            int linha = jtProdutos.getSelectedRow();
            int codigoTipo = (int) jtProdutos.getValueAt(linha, 0);
            produto.setCod_produto(codigoTipo);
            dadosProduto.removerProduto(produto);

        } catch (Exception e) {
        }
        limparCampos();
        carregarProdutos();


    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // Atualiza as duas palnilhas:
        carregarTipos();
        carregarProdutos();

    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jrbDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDisponivelActionPerformed
        // TODO add your handling code here:
        jrbIndisponivel.setSelected(false);
    }//GEN-LAST:event_jrbDisponivelActionPerformed

    private void jrbIndisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIndisponivelActionPerformed
        // TODO add your handling code here:
        jrbDisponivel.setSelected(false);
    }//GEN-LAST:event_jrbIndisponivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastraProdutos().setVisible(true);
            }
        });
    }

    /**
     * Carregar os tipos do banco na tela
     */
    private void carregarTipos() {

        try {
            Tipo tipo = new Tipo();
            DefaultTableModel modelo = new DefaultTableModel();
            ArrayList<Tipo> listaTipos = dadosTipo.listarTipo(tipo);

            modelo.setColumnIdentifiers(new Object[]{"Código", "Tipo"});
            for (Tipo t : listaTipos) {
                modelo.addRow(new Object[]{t.getCod_tipo(), t.getDescricao()});
            }
            jtTipos.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }

    }

    /**
     * Lista os produtos do banco na tela
     */
    private void carregarProdutos() {

        try {
            Produto produto = new Produto();

            ArrayList<Produto> listaProdutos = new ArrayList<>();
            listaProdutos = dadosProduto.listar(produto);
            DefaultTableModel modelo = new DefaultTableModel();

            modelo.setColumnIdentifiers(new Object[]{"Código", "Descrição", "Tipo", "Disponibilidade", "Valor(R$)"});
            for (Produto p : listaProdutos) {
                modelo.addRow(new Object[]{p.getCod_produto(), p.getNome(), p.getTipo().getDescricao(), p.getDisponibilidade(), p.getValorUnitario()});
            }
            jtProdutos.setModel(modelo);

        } catch (Exception ex) {
            Logger.getLogger(TelaCadastraProdutos.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    /*
        Limpa o campo para a próxima ação.
     */
    private void limparCampos() {
        jtfProduto.setText("");
        jtfPreco.setText("");
        jrbIndisponivel.setSelected(false);
        jrbDisponivel.setSelected(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JRadioButton jrbDisponivel;
    private javax.swing.JRadioButton jrbIndisponivel;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JTable jtTipos;
    private javax.swing.JTextField jtfPreco;
    private javax.swing.JTextField jtfProduto;
    // End of variables declaration//GEN-END:variables
}
