/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import produto.DadosProduto;
import produto.Produto;
import produto.RegrasProduto;
import tipo.DadosTipo;
import tipo.Tipo;

/**
 *
 * @author lgdal
 */
public class TelaCadastraProdutos1 extends javax.swing.JFrame {

    Tipo tipo = new Tipo();
    DadosTipo dadosTipo = new DadosTipo();
    ArrayList<DadosTipo> listaDadosTipos = new ArrayList<>();

    Produto produto = new Produto();
    DadosProduto dadosProduto = new DadosProduto();
    ArrayList<DadosProduto> listaDadosProduto = new ArrayList<>();

    RegrasProduto regrasProduto = new RegrasProduto();

    //Variável que irá receber o valor do código capturado na linha 427
    int codProduto = 0;

    /**
     * Creates new form TelaCadastraTipos
     */
    public TelaCadastraProdutos1() {
        initComponents();
        carregarTipos();
        carregarProdutos();
        setLocationRelativeTo(null);

        jbCadastrar.setVerticalTextPosition(SwingConstants.BOTTOM);
        jbCadastrar.setHorizontalTextPosition(SwingConstants.CENTER);
        jbAlterar.setVerticalTextPosition(SwingConstants.BOTTOM);
        jbAlterar.setHorizontalTextPosition(SwingConstants.CENTER);
        jbSalvarAlteracao.setVerticalTextPosition(SwingConstants.BOTTOM);
        jbSalvarAlteracao.setHorizontalTextPosition(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfProduto = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTipos = new javax.swing.JTable();
        jrbIndisponivel = new javax.swing.JRadioButton();
        jrbDisponivel = new javax.swing.JRadioButton();
        jbAtualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbAlterar = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jbSalvarAlteracao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRODUTO");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Tipo", "Disponibilidade", "Valor(R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProdutos);
        if (jtProdutos.getColumnModel().getColumnCount() > 0) {
            jtProdutos.getColumnModel().getColumn(0).setMinWidth(100);
            jtProdutos.getColumnModel().getColumn(0).setPreferredWidth(100);
            jtProdutos.getColumnModel().getColumn(0).setMaxWidth(100);
            jtProdutos.getColumnModel().getColumn(2).setMinWidth(130);
            jtProdutos.getColumnModel().getColumn(2).setPreferredWidth(130);
            jtProdutos.getColumnModel().getColumn(2).setMaxWidth(130);
            jtProdutos.getColumnModel().getColumn(3).setMinWidth(130);
            jtProdutos.getColumnModel().getColumn(3).setPreferredWidth(130);
            jtProdutos.getColumnModel().getColumn(3).setMaxWidth(130);
            jtProdutos.getColumnModel().getColumn(4).setMinWidth(100);
            jtProdutos.getColumnModel().getColumn(4).setPreferredWidth(100);
            jtProdutos.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Produto:");

        jtfProduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProdutoActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-cancelar-34.png"))); // NOI18N
        jbCancelar.setText("CANCELAR");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-lixo-34.png"))); // NOI18N
        jbExcluir.setText("EXCLUIR");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Preço (R$):");

        jtfPreco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jtTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtTipos);
        if (jtTipos.getColumnModel().getColumnCount() > 0) {
            jtTipos.getColumnModel().getColumn(0).setMinWidth(130);
            jtTipos.getColumnModel().getColumn(0).setPreferredWidth(130);
            jtTipos.getColumnModel().getColumn(0).setMaxWidth(130);
        }

        jrbIndisponivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbIndisponivel.setForeground(new java.awt.Color(204, 204, 204));
        jrbIndisponivel.setText("Indisponível");
        jrbIndisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIndisponivelActionPerformed(evt);
            }
        });

        jrbDisponivel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbDisponivel.setForeground(new java.awt.Color(204, 204, 204));
        jrbDisponivel.setText("Disponível");
        jrbDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDisponivelActionPerformed(evt);
            }
        });

        jbAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-actualizar-40.png"))); // NOI18N
        jbAtualizar.setText("ATUALIZAR");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-voltar-50.png"))); // NOI18N
        jbAlterar.setText("ALTERAR");
        jbAlterar.setIconTextGap(1);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-avançar-50.png"))); // NOI18N
        jbCadastrar.setText("CADASTRAR");
        jbCadastrar.setIconTextGap(1);
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbSalvarAlteracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-avançar-50.png"))); // NOI18N
        jbSalvarAlteracao.setText("ATUALIZAR");
        jbSalvarAlteracao.setIconTextGap(1);
        jbSalvarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarAlteracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, Short.MAX_VALUE)
            .addComponent(jbSalvarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jbCadastrar)
                .addGap(47, 47, 47)
                .addComponent(jbAlterar)
                .addGap(50, 50, 50)
                .addComponent(jbSalvarAlteracao)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Código:");

        jtfCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jbAtualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfProduto)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jrbDisponivel)
                                    .addGap(290, 290, 290)
                                    .addComponent(jrbIndisponivel))
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)
                            .addComponent(jtfPreco))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbIndisponivel)
                    .addComponent(jrbDisponivel))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluir)
                    .addComponent(jbCancelar)
                    .addComponent(jbAtualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:

        try {

            produto.setNome(jtfProduto.getText());

            if (jrbDisponivel.isSelected()) {
                produto.setDisponibilidade("Sim");
            } else {
                produto.setDisponibilidade("Faltando");
            }

            produto.setValorUnitario(Double.valueOf(jtfPreco.getText()));

            int linha = jtTipos.getSelectedRow();
            int codigoTipo = (int) jtTipos.getValueAt(linha, 0);
            String descricao = (String) jtTipos.getValueAt(linha, 1);

            tipo.setCod_tipo(codigoTipo);
            tipo.setDescricao(descricao);

            produto.setTipo(tipo);

            regrasProduto.cadastrarProduto(produto);

            carregarTipos();
            carregarProdutos();
            limparCampos();

        } catch (Exception ex) {
            //Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        carregarTipos();
        limparCampos();

    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:

        try {
            int linha = jtProdutos.getSelectedRow();
            int codigoTipo = (int) jtProdutos.getValueAt(linha, 0);
            produto.setCod_produto(codigoTipo);
            regrasProduto.removerProduto(produto);

            limparCampos();
            carregarProdutos();

        } catch (Exception ex) {
            //Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // Atualiza as duas palnilhas:
        carregarTipos();
        carregarProdutos();

    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jrbDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDisponivelActionPerformed
        // TODO add your handling code here:
        jrbIndisponivel.setSelected(false);
    }//GEN-LAST:event_jrbDisponivelActionPerformed

    private void jrbIndisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIndisponivelActionPerformed
        // TODO add your handling code here:
        jrbDisponivel.setSelected(false);
    }//GEN-LAST:event_jrbIndisponivelActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:

        try {

            Produto p = new Produto();
            int linha = jtProdutos.getSelectedRow();
            p.setCod_produto((int) jtProdutos.getValueAt(linha, 0));
            p.setNome((String) jtProdutos.getValueAt(linha, 1));
            p.setValorUnitario((double) jtProdutos.getValueAt(linha, 4));

            if ((jtProdutos.getValueAt(linha, 3)).equals("Sim")) {
                jrbDisponivel.setSelected(true);
                jrbIndisponivel.setSelected(false);
            } else {
                jrbDisponivel.setSelected(false);
                jrbIndisponivel.setSelected(true);
            }

            //Rotina para selecionar na tabela de tipos que corresponde ao tipo do produto que será alterado.
            String nomeTipoTabelaProduto = (String) jtProdutos.getValueAt(linha, 2);
            int tamanho = jtTipos.getRowCount();
            for (int i = 0; i <= tamanho; i++) {

                String nomeTipoTabelaTipo = (String) jtTipos.getValueAt(i, 1);

                if (nomeTipoTabelaProduto.equals(nomeTipoTabelaTipo)) {
                    jtTipos.getSelectionModel().addSelectionInterval(i, i);
                    break;

                }
            }

            jtfCodigo.setText(String.valueOf(p.getCod_produto()));
            jtfProduto.setText(p.getNome());
            jtfPreco.setText(String.valueOf(p.getValorUnitario()));

        } catch (Exception ex) {
            Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbSalvarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarAlteracaoActionPerformed
        // TODO add your handling code here:

        try {

            produto.setCod_produto(Integer.parseInt(jtfCodigo.getText()));
            produto.setNome(jtfProduto.getText());

            if (jrbDisponivel.isSelected()) {
                produto.setDisponibilidade("Sim");
            } else {
                produto.setDisponibilidade("Faltando");
            }

            produto.setValorUnitario(Double.valueOf(jtfPreco.getText()));

            int linhaTipo = jtTipos.getSelectedRow();
            int codigoTipo = (int) jtTipos.getValueAt(linhaTipo, 0);
            String descricao = (String) jtTipos.getValueAt(linhaTipo, 1);

            tipo.setCod_tipo(codigoTipo);
            tipo.setDescricao(descricao);

            produto.setTipo(tipo);

            regrasProduto.editarProduto(produto);

            carregarProdutos();

            limparCampos();

        } catch (Exception ex) {
            //Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbSalvarAlteracaoActionPerformed

    private void jtfProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastraProdutos1().setVisible(true);
            }
        });
    }

    /**
     * Carregar os tipos do banco na tela
     */
    private void carregarTipos() {

        try {
            Tipo tipo = new Tipo();
            DefaultTableModel modelo = new DefaultTableModel();
            ArrayList<Tipo> listaTipos = dadosTipo.listarTipo(tipo);

            modelo.setColumnIdentifiers(new Object[]{"Código", "Tipo"});
            for (Tipo t : listaTipos) {
                modelo.addRow(new Object[]{t.getCod_tipo(), t.getDescricao()});
            }
            jtTipos.setModel(modelo);

        } catch (Exception ex) {
            //Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    /**
     * Lista os produtos do banco na tela
     */
    private void carregarProdutos() {

        try {
            Produto produto = new Produto();

            ArrayList<Produto> listaProdutos = new ArrayList<>();
            listaProdutos = dadosProduto.listar(produto);
            DefaultTableModel modelo = new DefaultTableModel();

            modelo.setColumnIdentifiers(new Object[]{"Código", "Descrição", "Tipo", "Disponibilidade", "Valor(R$)"});
            for (Produto p : listaProdutos) {
                modelo.addRow(new Object[]{p.getCod_produto(), p.getNome(), p.getTipo().getDescricao(), p.getDisponibilidade(), p.getValorUnitario()});
            }
            jtProdutos.setModel(modelo);
            
            //Coloca a tabela na ordem que clicar na coluna
            jtProdutos.setAutoCreateRowSorter(true);
            

        } catch (Exception ex) {
            //Logger.getLogger(TelaCadastraProdutos1.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    /*
        Limpa o campo para a próxima ação.
     */
    private void limparCampos() {
        jtfProduto.setText("");
        jtfPreco.setText("");
        jtfCodigo.setText("");
        jrbIndisponivel.setSelected(false);
        jrbDisponivel.setSelected(false);
        jtTipos.clearSelection();
        //jtTipos.getSelectionModel().addSelectionInterval(1, 1);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbSalvarAlteracao;
    private javax.swing.JRadioButton jrbDisponivel;
    private javax.swing.JRadioButton jrbIndisponivel;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JTable jtTipos;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfPreco;
    private javax.swing.JTextField jtfProduto;
    // End of variables declaration//GEN-END:variables
}
